### PR TITLE
Add red and blue Wiis

### PR DESCRIPTION
**Pull request by 466gaming**
Add red and blue Wiis to `wii.guide/start`. Colours, woo

### CODE REVIEW

**Comment by Abequinn** [comment]
its really needed huh

**Comment by 466gaming** [comment]
yes

**Comment by Abequinn** [comment]
there is a reason why its black and white
white ones are a little different (boot2)

**Comment by 466gaming** [comment]
blue ones are a little different (no gamecube support)

**Comment by larsenv** [comment]
There's no point, but just for colors and to make it more overwhelming why not

**Pull request merged**
