### PR TITLE
WiiWare Patcher tutorial added.

### PR DESCRIPTION
**Pull request by KcrPL**
I know, sorry for 18 commits.

Good job KcrPL!

### CODE REVIEW

**Comment by larsenv** [comment]
You REALLY need to learn how to properly use GitHub.

**Comment by DarkPhoenix10** [comment]
kek

**Comment by KcrPL** [comment]
@larsenv

**Comment by DarkPhoenix10** [comment]
you really are addicted to them gifs are you

**Comment by KcrPL** [comment]
Gifs are just helping. Sometimes text isn't enough ;)

**Comment by DarkPhoenix10** [comment]
~~Text is not enough, use GIFS!~~

**Comment by DarkPhoenix10** [comment]
ok

**Comment by DarkPhoenix10** [comment]
memeslol

**Pull request merged**
